TOURISTS_GROUP_SPEED = 6# m/s
PARTICLES_NUM = 15
PSO_ITER_COUNT = 1000
UNCHANGED_SEQ_LEN = 10
CLUSTERING_ITER_COUNT = 50
S_P = 5
S_G = 10
GR_ROBOT_TIME_COEF = 1.5
ROBOTS_COUNT = 12
MAX_NET_DIST = 30
NODE_DIST = MAX_NET_DIST * 0.9
BUSY_ROBOTS_COUNT = 3

EQUIP_COUNT = 5
MED_EQUIP_COUNT = 2
AMOUNT_OF_GARBAGE = 15
NUMBER_OF_MODULES = 2

DETECTION_ANGLE = 75
DETECTION_DIST = 4
COLLECT_DIST = 2
